### PR TITLE
Use iTunes artworks when possible

### PR DESCRIPTION
**Pull request by sfavot**
Most of the songs I have on iTunes have artworks that can't be found on last.fm or custom ones that I added myself in iTunes. This PR aims to use iTunes artworks directly instead of retrieving them from last.fm. Widget behavior doesn't change when using Spotify.

Most of the changes are in the file `Get Current Track.applescript` for which the changes cannot be seen in GitHub as it's a binary file. If you want to check them, you can pull the branch then add

```
*.applescript diff=applescript
```

to the .git/info/attributes file of the project and

```
[diff "applescript"]
    textconv = osadecompile
    binary=true
```

to your .gitconfig file. You should then be able to see the diff of this file using `git diff`.

I'm submitting this because I think it could be useful for other users but of course feel free to dispose of it in the way you want.

### CODE REVIEW

**Comment by Pe8er** [comment]
Funny coincidence, I've added the exact same functionality 3 days ago 👍 My code is very similar to yours, I just added a provision to grab Last.fm artwork if the song played is in Apple Music (local artwork is not available then) and some other tweaks which _I hope_ make it more bomb-proof.

Since I'm not very experienced with Github, can you please help me figure out what's the correct / accepted way to resolve such a situation? It doesn't look like any of the merge options (merge, squash, rebase) apply here. Or maybe I close your request and commit my code? Or commit mine to a new branch, merge yours and we can compare? Pls halp!

**Comment by sfavot** [comment]
Yeah let's compare and take the best of both. 😊 You don't have to merge my PR to compare, just push your branch and we will be able to compare them on GitHub directly.

**Comment by Pe8er** [comment]
@sfavot I pushed stuff, please check it out ↑

**Comment by sfavot** [comment]
I'll be abroad with no network (or flaky one anyway) for 2 weeks so I'll check it out when I come back!

**Comment by sfavot** [comment]
I finally took the time to check what you did for the artworks. It's working perfectly so this PR is now useless. 😄 You can close it!

**Pull request closed without merging**
