### PR TITLE
Added Spotify Album Artwork Support

### PR DESCRIPTION
**Pull request by DenizUgur**
**Just a couple of adjustments to obey *new Authentication rules by Spotify Web API*.**

~~This pull request disables iTunes support with just a couple of adjustments this could be fixed 😄~~

Great widget btw, @Pe8er 😄

### CODE REVIEW

**Comment by Pe8er** [comment]
Hi there! Thank you for the submission. This is good stuff — I don't use Spotify, so I didn't know rules changed (again!!) I'm not a big fan of mixing JS with AppleScript to be honest. I will look at your code and try to incorporate it into the main AppleScript. Or perhaps I'll figure out a way to make the script independent of Spotify, the fact that it needs to be adjusted all the time is becoming annoying :)

**Comment by Pe8er** [comment]
I just remembered I actually got rid of Spotify API dependency a while ago… just forgot to publish it as a release. Please check it out: https://github.com/Pe8er/Playbox.widget/releases/latest

**Comment by DenizUgur** [comment]
@Pe8er maybe this could be sub-release that include Spotify API?

**Comment by DenizUgur** [comment]
Also I can maintain the Spotify dependency. Spotify is my main music player so I'm willing to take car of the API 😄

**Comment by Pe8er** [comment]
I'm sorry but I can't quite see the benefit of switching back to Spotify API. Last.fm has been rock-solid and I'd prefer to keep it that way. You are more than welcome to release your version of the widget 🍻 😃

**Comment by DenizUgur** [comment]
Done. Download from here -> [Spotify Integration](https://github.com/DenizUgur/Playbox.widget/raw/master/Playbox.widget.zip)

**Comment by DenizUgur** [comment]
I have published into my fork

**Pull request closed without merging**
